version: '3.8'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./stress-test:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ./stress-test:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master