version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - embeddings
    networks:
      - llm-network
    env_file:
      - envfile.txt

  embeddings:
    build:
      args:
        DOCKER_BUILDKIT: 1
      context: .
    ports:
      - "11434:11434"
    networks:
      - llm-network
    env_file:
      - envfile.txt

networks:
  llm-network:
